import type { Metadata } from "next";
import AuthImage from "./_components/AuthImage";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container mx-auto max-w-screen-xl flex flex-col lg:flex-row items-center justify-start gap-8 py-12 px-4 lg:px-8  shadow-lg rounded-lg bg-white" >
        {children}
        <AuthImage />
    </div>
  );
}
