import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import BreadCrumb from "@/components/BreadCrumb";
import SideBar from "./_components/SideBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <Header/>
        <BreadCrumb/>
        <main className="max-w-screen-xl container mx-auto flex flex-col gap-6 lg:flex-row mt-[48px]" >
            <SideBar/>
            {children}
        </main>
        <Footer/>
    </>
  );
}
