import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { Marcellus } from "next/font/google"
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const marcellus = Marcellus({
  style:'normal',
  weight:['400'],
  subsets:["latin"],
  display:"auto",
  variable:'--marcellus-font'
})
export const metadata: Metadata = {
  title: "GreenNature",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[#F6F6F6]`}
      >
        {children}
      </body>
    </html>
  );
}
