import type { Metadata } from "next";
import { Marcellus } from "next/font/google";
import "./globals.css";

const marcellus = Marcellus({
  weight: '400',
  style: "normal",
  subsets: ["latin"],
  preload: true,
})


export const metadata: Metadata = {
  title: "Greennature",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marcellus.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
