import type { Metadata } from "next";
<<<<<<< HEAD
import { Marcellus } from "next/font/google";
import "./globals.css";

const marcellus = Marcellus({
  weight: '400',
  style: "normal",
  subsets: ["latin"],
=======
import { Marcellus } from "next/font/google"
import "./globals.css";

const marcellus = Marcellus({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  display: "auto",
>>>>>>> 1801d73f6733141360c319e288dc45ead107c40b
  preload: true,
})


export const metadata: Metadata = {
  title: "Greennature",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marcellus.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
