import type { Metadata } from "next";
import { Marcellus } from "next/font/google"

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Breadcrumb from "@/components/Breadcrumb";
import Sidebar from "./_components/Sidebar";

const marcellus = Marcellus({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  display: "auto",
  preload: true,
})


export const metadata: Metadata = {
  title: "Greennature",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marcellus.className} antialiased`}
      >
        {/* <Header /> */}
        <Breadcrumb />
        <div className="max-w-screen-xl font-marcellus container mx-auto flex flex-col gap-6 lg:flex-row mt-[48px]">
            <Sidebar/>
            {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
